### ISSUE TITLE
How to debug scripts?

### ISSUE THREAD

**Issue by drewish** [RedL0tus/trigger#5]
I'm trying to use trigger to build a static website after a commit but having a problem. The info logging indicates it exited but doesn't show any output or the process's exit code. I'd tried both the options in the config but it didn't seem to have an effect. 

Is there an environment variable I can set to get more information?

**Comment by RedL0tus** [comment]
Could you please give me a look at your configuration file？ There may also be some useful information in GitHub's Webhook Settings page.

For debugging purpose, I personally suggest to write a separate script for generating the site, and only use use trigger to call that script. It would be a little easier to locate the issue this way.

**Comment by drewish** [comment]
Definitely
```yaml
settings:
  host: 0.0.0.0:4567
  secret: "yup some secret"
  print_commands: true
  capture_output: true

events:
  push: |
    set -e;
    cd multivac;
    export PATH="/home/amorton/.rbenv/shims:/home/amorton/.rbenv/bin:$PATH";
    bundle exec jekyll build --config _config.yml --destination /var/www/multivac/ --trace
```
Then running it while it accepts a webhook:
```
$ ./trigger --config trigger.conf 
 INFO  trigger > Listening on IPv4 address 0.0.0.0:4567
 INFO  trigger > Started
 INFO  trigger > Received "push" event from GitHub
 INFO  trigger > Delivery ID: "a0872850-c6d4-11ea-98c9-2e89e8917ae5"
 INFO  trigger > Running commands in "push" section
 INFO  trigger > Returning 200
 INFO  trigger > Commands in "push" section exited
```
On the GitHub side they just simply show:

**Headers**
```
Content-Length: 2
Date: Wed, 15 Jul 2020 20:14:33 GMT
```
**Body**
```
OK
```
